export interface Quote {
  id: string;
  companyName: string;
  industry: string;
  companySize: number;
  sourceOfQuote: string;
  status: 'Won' | 'Lost';
  lossReason?: string;
  quoteDate: string;
  premium: number;
}

export interface BrokerDetails {
  id: string;
  name: string;
  avgHeadcount: number;
  topIndustry: string;
  topQuoteSource: string;
  closeRate: number;
  quotes: Quote[];
}

export const brokerDetailsData: Record<string, BrokerDetails> = {
  'John Smith': {
    id: 'john-smith',
    name: 'John Smith',
    avgHeadcount: 125,
    topIndustry: 'Technology',
    topQuoteSource: 'Warm referrals',
    closeRate: 68,
    quotes: [
      {
        id: 'js-001',
        companyName: 'TechCorp Solutions',
        industry: 'Technology',
        companySize: 180,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-11-15',
        premium: 28500,
      },
      {
        id: 'js-002',
        companyName: 'Manufacturing Plus',
        industry: 'Manufacturing',
        companySize: 95,
        sourceOfQuote: 'Cold outreach',
        status: 'Lost',
        lossReason: 'Price too high - client found cheaper alternative with basic coverage',
        quoteDate: '2024-11-08',
        premium: 15200,
      },
      {
        id: 'js-003',
        companyName: 'Digital Innovations',
        industry: 'Technology',
        companySize: 220,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-10-28',
        premium: 42800,
      },
      {
        id: 'js-004',
        companyName: 'RetailMax Inc',
        industry: 'Retail',
        companySize: 85,
        sourceOfQuote: 'Events',
        status: 'Lost',
        lossReason: 'Timing not right - company undergoing restructuring',
        quoteDate: '2024-10-22',
        premium: 18600,
      },
      {
        id: 'js-005',
        companyName: 'FinTech Startup',
        industry: 'Technology',
        companySize: 45,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-10-15',
        premium: 12400,
      },
      {
        id: 'js-006',
        companyName: 'Global Manufacturing',
        industry: 'Manufacturing',
        companySize: 310,
        sourceOfQuote: 'Partnerships',
        status: 'Won',
        quoteDate: '2024-10-10',
        premium: 58200,
      },
      {
        id: 'js-007',
        companyName: 'Local Services Co',
        industry: 'Professional Services',
        companySize: 65,
        sourceOfQuote: 'Cold outreach',
        status: 'Lost',
        lossReason: 'Went with existing broker - long-standing relationship',
        quoteDate: '2024-09-30',
        premium: 14800,
      },
    ],
  },
  'Emily Davis': {
    id: 'emily-davis',
    name: 'Emily Davis',
    avgHeadcount: 285,
    topIndustry: 'Healthcare',
    topQuoteSource: 'Existing clients',
    closeRate: 72,
    quotes: [
      {
        id: 'ed-001',
        companyName: 'Regional Medical Center',
        industry: 'Healthcare',
        companySize: 420,
        sourceOfQuote: 'Existing clients',
        status: 'Won',
        quoteDate: '2024-11-12',
        premium: 85400,
      },
      {
        id: 'ed-002',
        companyName: 'HealthTech Innovations',
        industry: 'Healthcare',
        companySize: 185,
        sourceOfQuote: 'Partnerships',
        status: 'Won',
        quoteDate: '2024-11-05',
        premium: 38200,
      },
      {
        id: 'ed-003',
        companyName: 'Finance Corp',
        industry: 'Finance',
        companySize: 250,
        sourceOfQuote: 'Existing clients',
        status: 'Lost',
        lossReason: 'Budget constraints - postponed decision for next fiscal year',
        quoteDate: '2024-10-25',
        premium: 52800,
      },
      {
        id: 'ed-004',
        companyName: 'Community Hospital',
        industry: 'Healthcare',
        companySize: 380,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-10-18',
        premium: 76500,
      },
      {
        id: 'ed-005',
        companyName: 'Med Device Solutions',
        industry: 'Healthcare',
        companySize: 95,
        sourceOfQuote: 'Events',
        status: 'Won',
        quoteDate: '2024-10-12',
        premium: 21800,
      },
      {
        id: 'ed-006',
        companyName: 'Insurance Services LLC',
        industry: 'Finance',
        companySize: 150,
        sourceOfQuote: 'Existing clients',
        status: 'Lost',
        lossReason: 'Competitor offered better terms - more flexible coverage options',
        quoteDate: '2024-10-08',
        premium: 32400,
      },
      {
        id: 'ed-007',
        companyName: 'Pharmacy Chain',
        industry: 'Healthcare',
        companySize: 280,
        sourceOfQuote: 'Existing clients',
        status: 'Won',
        quoteDate: '2024-09-28',
        premium: 58900,
      },
      {
        id: 'ed-008',
        companyName: 'Healthcare Analytics',
        industry: 'Healthcare',
        companySize: 120,
        sourceOfQuote: 'Partnerships',
        status: 'Won',
        quoteDate: '2024-09-22',
        premium: 26700,
      },
    ],
  },
  'Michael Johnson': {
    id: 'michael-johnson',
    name: 'Michael Johnson',
    avgHeadcount: 95,
    topIndustry: 'Manufacturing',
    topQuoteSource: 'Events',
    closeRate: 59,
    quotes: [
      {
        id: 'mj-001',
        companyName: 'Steel Works Inc',
        industry: 'Manufacturing',
        companySize: 145,
        sourceOfQuote: 'Events',
        status: 'Won',
        quoteDate: '2024-11-10',
        premium: 32800,
      },
      {
        id: 'mj-002',
        companyName: 'Auto Parts Manufacturing',
        industry: 'Manufacturing',
        companySize: 220,
        sourceOfQuote: 'Events',
        status: 'Lost',
        lossReason: 'Price too high - required significant cost reduction to match budget',
        quoteDate: '2024-11-03',
        premium: 48600,
      },
      {
        id: 'mj-003',
        companyName: 'Food Processing Co',
        industry: 'Manufacturing',
        companySize: 85,
        sourceOfQuote: 'Cold outreach',
        status: 'Won',
        quoteDate: '2024-10-26',
        premium: 19400,
      },
      {
        id: 'mj-004',
        companyName: 'Textile Solutions',
        industry: 'Manufacturing',
        companySize: 65,
        sourceOfQuote: 'Events',
        status: 'Lost',
        lossReason: 'Went with competitor - existing relationship with their current provider',
        quoteDate: '2024-10-20',
        premium: 14200,
      },
      {
        id: 'mj-005',
        companyName: 'Chemical Industries',
        industry: 'Manufacturing',
        companySize: 180,
        sourceOfQuote: 'Partnerships',
        status: 'Won',
        quoteDate: '2024-10-14',
        premium: 39800,
      },
      {
        id: 'mj-006',
        companyName: 'Construction Materials',
        industry: 'Construction',
        companySize: 120,
        sourceOfQuote: 'Events',
        status: 'Lost',
        lossReason: 'Timing not right - waiting for new safety regulations to be finalized',
        quoteDate: '2024-10-05',
        premium: 28500,
      },
      {
        id: 'mj-007',
        companyName: 'Packaging Solutions',
        industry: 'Manufacturing',
        companySize: 95,
        sourceOfQuote: 'Inbound website',
        status: 'Won',
        quoteDate: '2024-09-28',
        premium: 22100,
      },
    ],
  },
  'Sarah Williams': {
    id: 'sarah-williams',
    name: 'Sarah Williams',
    avgHeadcount: 310,
    topIndustry: 'Finance',
    topQuoteSource: 'Warm referrals',
    closeRate: 64,
    quotes: [
      {
        id: 'sw-001',
        companyName: 'Investment Bank Corp',
        industry: 'Finance',
        companySize: 450,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-11-08',
        premium: 92500,
      },
      {
        id: 'sw-002',
        companyName: 'Credit Union Alliance',
        industry: 'Finance',
        companySize: 280,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-11-01',
        premium: 58200,
      },
      {
        id: 'sw-003',
        companyName: 'Tech Consulting Group',
        industry: 'Professional Services',
        companySize: 185,
        sourceOfQuote: 'Events',
        status: 'Lost',
        lossReason: 'Budget constraints - reduced headcount affected premium calculations',
        quoteDate: '2024-10-24',
        premium: 42800,
      },
      {
        id: 'sw-004',
        companyName: 'Accounting Services LLC',
        industry: 'Professional Services',
        companySize: 95,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-10-16',
        premium: 24600,
      },
      {
        id: 'sw-005',
        companyName: 'Financial Planning Co',
        industry: 'Finance',
        companySize: 320,
        sourceOfQuote: 'Existing clients',
        status: 'Lost',
        lossReason: 'Competitor offered better terms - included additional wellness programs',
        quoteDate: '2024-10-10',
        premium: 68400,
      },
      {
        id: 'sw-006',
        companyName: 'Real Estate Holdings',
        industry: 'Real Estate',
        companySize: 150,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-10-02',
        premium: 35800,
      },
      {
        id: 'sw-007',
        companyName: 'Insurance Brokerage',
        industry: 'Finance',
        companySize: 220,
        sourceOfQuote: 'Partnerships',
        status: 'Lost',
        lossReason: 'Timing not right - waiting for merger completion to finalize benefits',
        quoteDate: '2024-09-25',
        premium: 52100,
      },
      {
        id: 'sw-008',
        companyName: 'Private Equity Fund',
        industry: 'Finance',
        companySize: 380,
        sourceOfQuote: 'Warm referrals',
        status: 'Won',
        quoteDate: '2024-09-18',
        premium: 78900,
      },
      {
        id: 'sw-009',
        companyName: 'Legal Services Group',
        industry: 'Professional Services',
        companySize: 125,
        sourceOfQuote: 'Events',
        status: 'Lost',
        lossReason: 'Price too high - needed to match competitor pricing by 15%',
        quoteDate: '2024-09-12',
        premium: 31200,
      },
    ],
  },
};